#!/usr/bin/env python

import sys

from rqt_gui.main import Main


def add_arguments(parser):
    group = parser.add_argument_group('Options for autonomos_line_calibration plugin')
    group.add_argument('topic', nargs='?', help='The topic name to subscribe to')

main = Main()
sys.exit(main.main(
    sys.argv,
    # standalone='rqt_image_view/ImageView',
    standalone='rqt_autonomos_line_calibration/line_calibration_plugin',
    plugin_argument_provider=add_arguments))